### ISSUE TITLE
About the annotation format

### ISSUE THREAD

**Issue by TuoniTuoni** [neuro-ml/midline-shift-detection#4]
Hello. How do you make the json annotation fromat? Now I get the nii.gz annotation format through using the ITK-SNAP label .dcm CT slices.  How I can get the JSON annotation then？ what should I do? thanks...

**Comment by maxme1** [comment]
Hi!
We didn't use ITK-SNAP for annotation, so I'm not sure how to extract the contours from the resulting `nii.gz` files.

**Comment by TuoniTuoni** [comment]
Ok, and what annotation tool  do you use? And for you annotation, every row and column only have one pixel been marked?

**Comment by maxme1** [comment]
We use an internal tool for annotation. 
Can you please clarify the second question? (:

**Comment by TuoniTuoni** [comment]
Sorry ,I want to express , if only one pixel is labeled to each row when label the medical image's brian midline?

**Comment by maxme1** [comment]
We annotate axial slices separately. On each slice we draw a curve as a vector image, so no pixels are being drawn, because, in case of curves, vector graphics are more appropriate and accurate. 
You could try and use raster graphics, in which case I would go with a single pixel per row/column (:
